<a href="https://colab.research.google.com/github/anujsonkar1526-coder/Data-Science-class-notes/blob/main/Class6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [6]:
dct={
    'name':['Tom','Nick','Krish','jack','Oggy'],
    'age':[20,10,40,50,80],
    'roll':[1,2,3,4,5]

}

df=pd.DataFrame(dct)
print(df)

display(df)

df=pd.DataFrame(dct, index=['a','b','c','d','e'])
print(df)

    name  age  roll
0    Tom   20     1
1   Nick   10     2
2  Krish   40     3
3   jack   50     4
4   Oggy   80     5

    name  age  roll
0    Tom   20     1
1   Nick   10     2
2  Krish   40     3
3   jack   50     4
4   Oggy   80     5

    name  age  roll
a    Tom   20     1
b   Nick   10     2
c  Krish   40     3
d   jack   50     4
e   Oggy   80     5

In [30]:
df=pd.read_csv('student_data.csv')

df.head()# its give first give value from the table bydefault 5 value given from the table

df.shape # its given the shape of table

df.tail()# its given the  last five  value from the table bydefault 5 value given from the table


df.info()

df.describe()#. First Quartile (Q₁): Also known as the lower quartile. It marks the 25th percentile, meaning 25% of the data lies below this point, and 75% lies above it.
                #Second Quartile (Q₂): This is the median of the dataset. It marks the 50th percentile, splitting the dataset exactly in half.
                #Third Quartile (Q₃): Also known as the upper quartile. It marks the 75th percentile, meaning 75% of the data lies below this value, and 25% lies above it.
                #The IQR is the difference between the third and first quartiles (Q₃ - Q₁).


df[['study_hours','internet_usage']] # table me se konsa data hume chahiye use aise nikala jata hai jitne data utne brakets[]
df['study_hours']

df.iloc[1] # we are access the particular row using it and jis roow ko access krna hai uska index dena hai. iloc apni inexing pe work krta hai
df.iloc[1:4] # we are access the row from 1 to

df.loc[df['study_hours']==11] # loc use for condition. loc ushi index ya lebel pe work krta hai joh table pe  actually present hota hai
df.loc[df['study_hours']==11,['study_hours','sleep_hours']].iloc[4:8]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

     study_hours  sleep_hours
30            11            5
91            11            9
98            11            6
116           11            7

In [51]:
df["age"]=20 #new data to table me add karna
df # print table

df=df.rename(columns={'assignments_completed':'assign_completed'}) # table me name ko change karrna pehla name jiske place pe change karna hai or secnd joh chnage karna hai
df # print table

df.drop(columns={'sleep_hours','exam_score'}) # remove  columns
df.drop(index=[1]) # remove rows

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
5,7,40,9,10,0,60,72.33,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [55]:
df.dropna()#its use for missing value




# 1. Drop any row containing a NaN value
df_clean = df.dropna()

# 2. Drop any column containing a NaN value
df_cols = df.dropna(axis=1)

In [26]:
# questions form table
df.loc[df['assignments_completed']==8].iloc[1]

df.loc[df['assignments_completed']>3]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed